HTTP:
  host: 'localhost'
  port: 3000
 
 # mysql
MYSQL_CONFIG:
  type: mysql # 数据库链接类型
  host: 47.99.93.97
  port: 8836
  username: "root" # 数据库链接用户名
  password: "admin123456***" # 数据库链接密码
  database: "nest-study" # 数据库名
  logging: true # 数据库打印日志
  synchronize: false # 是否开启同步数据表功能
  autoLoadEntities: true # 是否自动加载实体
