HTTP:
  host: 'localhost'
  port: 3001
VERSION:
  index: 1

# jwt
JWT:
  secret: wxfiang@qq.com
  signOptions:
    expiresIn: 360000s

 # mysql
MYSQL_CONFIG:
  type: mysql # 数据库链接类型
  host: 47.99.93.97
  port: 8836
  username: "root" # 数据库链接用户名
  password: "admin123456***" # 数据库链接密码
  database: "nest-study" # 数据库名
  logging: true # 数据库打印日志
  synchronize: false # 是否开启同步数据表功能
  autoLoadEntities: true # 是否自动加载实体

# session
SESSION:
  secret: "wxfeiang@qq.com"
  maxAge:  1800000  #3 * 60 * 1000
  maxEmail: 1800000

# email
EMAIL:
  host: "smtp.qq.com"
  port: 587
  user: "wxfeiang@foxmail.com"
  pass: "gkebybwwdekdjggc"
  sendName: 'Nesr.js 测试管理系统'


# throttler
THROTTLER:
  ttl: 60,   #1分钟
  limit: 10, #请求10次