HTTP:
  host: 'localhost'
  port: 3000
 
 # mysql
MYSQL_CONFIG:
  type: mysql # 数据库链接类型
  host: localhost
  port: 3306
  username: "root" # 数据库链接用户名
  password: "你的数据库密码" # 数据库链接密码
  database: "nest-study" # 数据库名
  logging: true # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
  autoLoadEntities: true # 是否自动加载实体
